M48
; DRILL file {KiCad (6.0.10)} date Fri Feb 10 12:49:50 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-10T12:49:50-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0984
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1378
%
G90
G05
T1
X4.8Y-1.9
X4.8Y-5.2
X6.745Y-5.19
X6.77Y-1.915
T2
X5.4243Y-2.045
T0
M30
